//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.strikeiron.com", ConfigurationName="CurrencyRatesSoap")]
public interface CurrencyRatesSoap
{
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetLatestRate", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
    System.Threading.Tasks.Task<GetLatestRateResponse> GetLatestRateAsync(GetLatestRateRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetLatestRates", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
    System.Threading.Tasks.Task<GetLatestRatesResponse> GetLatestRatesAsync(GetLatestRatesRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/CurrencyRateForAmount", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
    System.Threading.Tasks.Task<CurrencyRateForAmountResponse> CurrencyRateForAmountAsync(CurrencyRateForAmountRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetHistoricalRates", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
    System.Threading.Tasks.Task<GetHistoricalRatesResponse> GetHistoricalRatesAsync(GetHistoricalRatesRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetHistoricalRate", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
    System.Threading.Tasks.Task<GetHistoricalRateResponse> GetHistoricalRateAsync(GetHistoricalRateRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetAllLatestRatesToUSD", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
    System.Threading.Tasks.Task<GetAllLatestRatesToUSDResponse> GetAllLatestRatesToUSDAsync(GetAllLatestRatesToUSDRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetAllLatestUSDToCurrencies", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
    System.Threading.Tasks.Task<GetAllLatestUSDToCurrenciesResponse> GetAllLatestUSDToCurrenciesAsync(GetAllLatestUSDToCurrenciesRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetSupportedCurrencies", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
    System.Threading.Tasks.Task<GetSupportedCurrenciesResponse> GetSupportedCurrenciesAsync(GetSupportedCurrenciesRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetStatusCodesForMethod", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
    System.Threading.Tasks.Task<GetStatusCodesForMethodResponse> GetStatusCodesForMethodAsync(GetStatusCodesForMethodRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetStatusCodes", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
    System.Threading.Tasks.Task<GetStatusCodesResponse> GetStatusCodesAsync(GetStatusCodesRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetServiceInfo", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
    System.Threading.Tasks.Task<GetServiceInfoResponse> GetServiceInfoAsync(GetServiceInfoRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://wsparam.strikeiron.com/StrikeIron/ForeignExchangeRate3/CurrencyRates/GetRe" +
        "mainingHits", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
    System.Threading.Tasks.Task<GetRemainingHitsResponse> GetRemainingHitsAsync(GetRemainingHitsRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public partial class SIWsOutputOfExchangeRate
{
    
    private SIWsStatus serviceStatusField;
    
    private ExchangeRate serviceResultField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SIWsStatus ServiceStatus
    {
        get
        {
            return this.serviceStatusField;
        }
        set
        {
            this.serviceStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ExchangeRate ServiceResult
    {
        get
        {
            return this.serviceResultField;
        }
        set
        {
            this.serviceResultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public partial class SIWsStatus
{
    
    private int statusNbrField;
    
    private string statusDescriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int StatusNbr
    {
        get
        {
            return this.statusNbrField;
        }
        set
        {
            this.statusNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string StatusDescription
    {
        get
        {
            return this.statusDescriptionField;
        }
        set
        {
            this.statusDescriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public partial class ServiceInfoRecord
{
    
    private string infoKeyField;
    
    private string infoValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string InfoKey
    {
        get
        {
            return this.infoKeyField;
        }
        set
        {
            this.infoKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string InfoValue
    {
        get
        {
            return this.infoValueField;
        }
        set
        {
            this.infoValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public partial class SIWsResultArrayOfServiceInfoRecord
{
    
    private ServiceInfoRecord[] resultsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    public ServiceInfoRecord[] Results
    {
        get
        {
            return this.resultsField;
        }
        set
        {
            this.resultsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public partial class SIWsOutputOfSIWsResultArrayOfServiceInfoRecord
{
    
    private SIWsStatus serviceStatusField;
    
    private SIWsResultArrayOfServiceInfoRecord serviceResultField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SIWsStatus ServiceStatus
    {
        get
        {
            return this.serviceStatusField;
        }
        set
        {
            this.serviceStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public SIWsResultArrayOfServiceInfoRecord ServiceResult
    {
        get
        {
            return this.serviceResultField;
        }
        set
        {
            this.serviceResultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public partial class SIWsResultArrayOfMethodStatusRecord
{
    
    private MethodStatusRecord[] resultsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    public MethodStatusRecord[] Results
    {
        get
        {
            return this.resultsField;
        }
        set
        {
            this.resultsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public partial class MethodStatusRecord : SIWsResultArrayOfSIWsStatus
{
    
    private string methodNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string MethodName
    {
        get
        {
            return this.methodNameField;
        }
        set
        {
            this.methodNameField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MethodStatusRecord))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public partial class SIWsResultArrayOfSIWsStatus
{
    
    private SIWsStatus[] resultsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    public SIWsStatus[] Results
    {
        get
        {
            return this.resultsField;
        }
        set
        {
            this.resultsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public partial class SIWsOutputOfSIWsResultArrayOfMethodStatusRecord
{
    
    private SIWsStatus serviceStatusField;
    
    private SIWsResultArrayOfMethodStatusRecord serviceResultField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SIWsStatus ServiceStatus
    {
        get
        {
            return this.serviceStatusField;
        }
        set
        {
            this.serviceStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public SIWsResultArrayOfMethodStatusRecord ServiceResult
    {
        get
        {
            return this.serviceResultField;
        }
        set
        {
            this.serviceResultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public partial class SIWsOutputOfMethodStatusRecord
{
    
    private SIWsStatus serviceStatusField;
    
    private MethodStatusRecord serviceResultField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SIWsStatus ServiceStatus
    {
        get
        {
            return this.serviceStatusField;
        }
        set
        {
            this.serviceStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public MethodStatusRecord ServiceResult
    {
        get
        {
            return this.serviceResultField;
        }
        set
        {
            this.serviceResultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public partial class CurrencyListing
{
    
    private string unitField;
    
    private string countryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Country
    {
        get
        {
            return this.countryField;
        }
        set
        {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public partial class SIWsResultArrayOfCurrencyListing
{
    
    private CurrencyListing[] resultsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    public CurrencyListing[] Results
    {
        get
        {
            return this.resultsField;
        }
        set
        {
            this.resultsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public partial class SIWsOutputOfSIWsResultArrayOfCurrencyListing
{
    
    private SIWsStatus serviceStatusField;
    
    private SIWsResultArrayOfCurrencyListing serviceResultField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SIWsStatus ServiceStatus
    {
        get
        {
            return this.serviceStatusField;
        }
        set
        {
            this.serviceStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public SIWsResultArrayOfCurrencyListing ServiceResult
    {
        get
        {
            return this.serviceResultField;
        }
        set
        {
            this.serviceResultField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExchangeRateListing))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public abstract partial class SIWsResultWithStatus
{
    
    private SIWsStatus itemStatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SIWsStatus ItemStatus
    {
        get
        {
            return this.itemStatusField;
        }
        set
        {
            this.itemStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public partial class ExchangeRateListing : SIWsResultWithStatus
{
    
    private double valueField;
    
    private string currencyField;
    
    private string perCurrencyField;
    
    private string dateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public double Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string PerCurrency
    {
        get
        {
            return this.perCurrencyField;
        }
        set
        {
            this.perCurrencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Date
    {
        get
        {
            return this.dateField;
        }
        set
        {
            this.dateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public partial class SIWsResultArrayOfExchangeRateListing
{
    
    private ExchangeRateListing[] resultsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    public ExchangeRateListing[] Results
    {
        get
        {
            return this.resultsField;
        }
        set
        {
            this.resultsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public partial class SIWsOutputOfSIWsResultArrayOfExchangeRateListing
{
    
    private SIWsStatus serviceStatusField;
    
    private SIWsResultArrayOfExchangeRateListing serviceResultField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SIWsStatus ServiceStatus
    {
        get
        {
            return this.serviceStatusField;
        }
        set
        {
            this.serviceStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public SIWsResultArrayOfExchangeRateListing ServiceResult
    {
        get
        {
            return this.serviceResultField;
        }
        set
        {
            this.serviceResultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public partial class SISubscriptionInfo
{
    
    private int licenseStatusCodeField;
    
    private string licenseStatusField;
    
    private int licenseActionCodeField;
    
    private string licenseActionField;
    
    private int remainingHitsField;
    
    private decimal amountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int LicenseStatusCode
    {
        get
        {
            return this.licenseStatusCodeField;
        }
        set
        {
            this.licenseStatusCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string LicenseStatus
    {
        get
        {
            return this.licenseStatusField;
        }
        set
        {
            this.licenseStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public int LicenseActionCode
    {
        get
        {
            return this.licenseActionCodeField;
        }
        set
        {
            this.licenseActionCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string LicenseAction
    {
        get
        {
            return this.licenseActionField;
        }
        set
        {
            this.licenseActionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public int RemainingHits
    {
        get
        {
            return this.remainingHitsField;
        }
        set
        {
            this.remainingHitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public decimal Amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
public partial class ExchangeRate
{
    
    private double valueField;
    
    private string currencyField;
    
    private string perCurrencyField;
    
    private string dateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public double Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string PerCurrency
    {
        get
        {
            return this.perCurrencyField;
        }
        set
        {
            this.perCurrencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Date
    {
        get
        {
            return this.dateField;
        }
        set
        {
            this.dateField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetLatestRate", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetLatestRateRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public string UnregisteredUserEmail;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public string UserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
    public string Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=3)]
    public string SingleCurrencyFrom;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=4)]
    public string SingleCurrencyTo;
    
    public GetLatestRateRequest()
    {
    }
    
    public GetLatestRateRequest(string UnregisteredUserEmail, string UserID, string Password, string SingleCurrencyFrom, string SingleCurrencyTo)
    {
        this.UnregisteredUserEmail = UnregisteredUserEmail;
        this.UserID = UserID;
        this.Password = Password;
        this.SingleCurrencyFrom = SingleCurrencyFrom;
        this.SingleCurrencyTo = SingleCurrencyTo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetLatestRateResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetLatestRateResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public SIWsOutputOfExchangeRate GetLatestRateResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public SISubscriptionInfo SISubscriptionInfo;
    
    public GetLatestRateResponse()
    {
    }
    
    public GetLatestRateResponse(SIWsOutputOfExchangeRate GetLatestRateResult, SISubscriptionInfo SISubscriptionInfo)
    {
        this.GetLatestRateResult = GetLatestRateResult;
        this.SISubscriptionInfo = SISubscriptionInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetLatestRates", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetLatestRatesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public string UnregisteredUserEmail;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public string UserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
    public string Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=3)]
    public string CommaSeparatedListOfCurrenciesFrom;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=4)]
    public string SingleCurrencyTo;
    
    public GetLatestRatesRequest()
    {
    }
    
    public GetLatestRatesRequest(string UnregisteredUserEmail, string UserID, string Password, string CommaSeparatedListOfCurrenciesFrom, string SingleCurrencyTo)
    {
        this.UnregisteredUserEmail = UnregisteredUserEmail;
        this.UserID = UserID;
        this.Password = Password;
        this.CommaSeparatedListOfCurrenciesFrom = CommaSeparatedListOfCurrenciesFrom;
        this.SingleCurrencyTo = SingleCurrencyTo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetLatestRatesResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetLatestRatesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetLatestRatesResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public SISubscriptionInfo SISubscriptionInfo;
    
    public GetLatestRatesResponse()
    {
    }
    
    public GetLatestRatesResponse(SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetLatestRatesResult, SISubscriptionInfo SISubscriptionInfo)
    {
        this.GetLatestRatesResult = GetLatestRatesResult;
        this.SISubscriptionInfo = SISubscriptionInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="CurrencyRateForAmount", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class CurrencyRateForAmountRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public string UnregisteredUserEmail;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public string UserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
    public string Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=3)]
    public string SingleCurrencyFrom;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=4)]
    public string SingleCurrencyTo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=5)]
    public string Amount;
    
    public CurrencyRateForAmountRequest()
    {
    }
    
    public CurrencyRateForAmountRequest(string UnregisteredUserEmail, string UserID, string Password, string SingleCurrencyFrom, string SingleCurrencyTo, string Amount)
    {
        this.UnregisteredUserEmail = UnregisteredUserEmail;
        this.UserID = UserID;
        this.Password = Password;
        this.SingleCurrencyFrom = SingleCurrencyFrom;
        this.SingleCurrencyTo = SingleCurrencyTo;
        this.Amount = Amount;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="CurrencyRateForAmountResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class CurrencyRateForAmountResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public SIWsOutputOfExchangeRate CurrencyRateForAmountResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public SISubscriptionInfo SISubscriptionInfo;
    
    public CurrencyRateForAmountResponse()
    {
    }
    
    public CurrencyRateForAmountResponse(SIWsOutputOfExchangeRate CurrencyRateForAmountResult, SISubscriptionInfo SISubscriptionInfo)
    {
        this.CurrencyRateForAmountResult = CurrencyRateForAmountResult;
        this.SISubscriptionInfo = SISubscriptionInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetHistoricalRates", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetHistoricalRatesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public string UnregisteredUserEmail;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public string UserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
    public string Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=3)]
    public string CommaSeparatedListOfCurrenciesFrom;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=4)]
    public string SingleCurrencyTo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=5)]
    public string Date;
    
    public GetHistoricalRatesRequest()
    {
    }
    
    public GetHistoricalRatesRequest(string UnregisteredUserEmail, string UserID, string Password, string CommaSeparatedListOfCurrenciesFrom, string SingleCurrencyTo, string Date)
    {
        this.UnregisteredUserEmail = UnregisteredUserEmail;
        this.UserID = UserID;
        this.Password = Password;
        this.CommaSeparatedListOfCurrenciesFrom = CommaSeparatedListOfCurrenciesFrom;
        this.SingleCurrencyTo = SingleCurrencyTo;
        this.Date = Date;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetHistoricalRatesResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetHistoricalRatesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetHistoricalRatesResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public SISubscriptionInfo SISubscriptionInfo;
    
    public GetHistoricalRatesResponse()
    {
    }
    
    public GetHistoricalRatesResponse(SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetHistoricalRatesResult, SISubscriptionInfo SISubscriptionInfo)
    {
        this.GetHistoricalRatesResult = GetHistoricalRatesResult;
        this.SISubscriptionInfo = SISubscriptionInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetHistoricalRate", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetHistoricalRateRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public string UnregisteredUserEmail;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public string UserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
    public string Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=3)]
    public string SingleCurrencyFrom;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=4)]
    public string SingleCurrencyTo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=5)]
    public string DateFrom;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=6)]
    public string DateTo;
    
    public GetHistoricalRateRequest()
    {
    }
    
    public GetHistoricalRateRequest(string UnregisteredUserEmail, string UserID, string Password, string SingleCurrencyFrom, string SingleCurrencyTo, string DateFrom, string DateTo)
    {
        this.UnregisteredUserEmail = UnregisteredUserEmail;
        this.UserID = UserID;
        this.Password = Password;
        this.SingleCurrencyFrom = SingleCurrencyFrom;
        this.SingleCurrencyTo = SingleCurrencyTo;
        this.DateFrom = DateFrom;
        this.DateTo = DateTo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetHistoricalRateResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetHistoricalRateResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetHistoricalRateResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public SISubscriptionInfo SISubscriptionInfo;
    
    public GetHistoricalRateResponse()
    {
    }
    
    public GetHistoricalRateResponse(SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetHistoricalRateResult, SISubscriptionInfo SISubscriptionInfo)
    {
        this.GetHistoricalRateResult = GetHistoricalRateResult;
        this.SISubscriptionInfo = SISubscriptionInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetAllLatestRatesToUSD", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetAllLatestRatesToUSDRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public string UnregisteredUserEmail;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public string UserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
    public string Password;
    
    public GetAllLatestRatesToUSDRequest()
    {
    }
    
    public GetAllLatestRatesToUSDRequest(string UnregisteredUserEmail, string UserID, string Password)
    {
        this.UnregisteredUserEmail = UnregisteredUserEmail;
        this.UserID = UserID;
        this.Password = Password;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetAllLatestRatesToUSDResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetAllLatestRatesToUSDResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetAllLatestRatesToUSDResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public SISubscriptionInfo SISubscriptionInfo;
    
    public GetAllLatestRatesToUSDResponse()
    {
    }
    
    public GetAllLatestRatesToUSDResponse(SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetAllLatestRatesToUSDResult, SISubscriptionInfo SISubscriptionInfo)
    {
        this.GetAllLatestRatesToUSDResult = GetAllLatestRatesToUSDResult;
        this.SISubscriptionInfo = SISubscriptionInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetAllLatestUSDToCurrencies", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetAllLatestUSDToCurrenciesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public string UnregisteredUserEmail;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public string UserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
    public string Password;
    
    public GetAllLatestUSDToCurrenciesRequest()
    {
    }
    
    public GetAllLatestUSDToCurrenciesRequest(string UnregisteredUserEmail, string UserID, string Password)
    {
        this.UnregisteredUserEmail = UnregisteredUserEmail;
        this.UserID = UserID;
        this.Password = Password;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetAllLatestUSDToCurrenciesResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetAllLatestUSDToCurrenciesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetAllLatestUSDToCurrenciesResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public SISubscriptionInfo SISubscriptionInfo;
    
    public GetAllLatestUSDToCurrenciesResponse()
    {
    }
    
    public GetAllLatestUSDToCurrenciesResponse(SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetAllLatestUSDToCurrenciesResult, SISubscriptionInfo SISubscriptionInfo)
    {
        this.GetAllLatestUSDToCurrenciesResult = GetAllLatestUSDToCurrenciesResult;
        this.SISubscriptionInfo = SISubscriptionInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetSupportedCurrencies", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetSupportedCurrenciesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public string UnregisteredUserEmail;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public string UserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
    public string Password;
    
    public GetSupportedCurrenciesRequest()
    {
    }
    
    public GetSupportedCurrenciesRequest(string UnregisteredUserEmail, string UserID, string Password)
    {
        this.UnregisteredUserEmail = UnregisteredUserEmail;
        this.UserID = UserID;
        this.Password = Password;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetSupportedCurrenciesResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetSupportedCurrenciesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public SIWsOutputOfSIWsResultArrayOfCurrencyListing GetSupportedCurrenciesResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public SISubscriptionInfo SISubscriptionInfo;
    
    public GetSupportedCurrenciesResponse()
    {
    }
    
    public GetSupportedCurrenciesResponse(SIWsOutputOfSIWsResultArrayOfCurrencyListing GetSupportedCurrenciesResult, SISubscriptionInfo SISubscriptionInfo)
    {
        this.GetSupportedCurrenciesResult = GetSupportedCurrenciesResult;
        this.SISubscriptionInfo = SISubscriptionInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusCodesForMethod", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetStatusCodesForMethodRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public string UnregisteredUserEmail;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public string UserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
    public string Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=3)]
    public string MethodName;
    
    public GetStatusCodesForMethodRequest()
    {
    }
    
    public GetStatusCodesForMethodRequest(string UnregisteredUserEmail, string UserID, string Password, string MethodName)
    {
        this.UnregisteredUserEmail = UnregisteredUserEmail;
        this.UserID = UserID;
        this.Password = Password;
        this.MethodName = MethodName;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusCodesForMethodResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetStatusCodesForMethodResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public SIWsOutputOfMethodStatusRecord GetStatusCodesForMethodResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public SISubscriptionInfo SISubscriptionInfo;
    
    public GetStatusCodesForMethodResponse()
    {
    }
    
    public GetStatusCodesForMethodResponse(SIWsOutputOfMethodStatusRecord GetStatusCodesForMethodResult, SISubscriptionInfo SISubscriptionInfo)
    {
        this.GetStatusCodesForMethodResult = GetStatusCodesForMethodResult;
        this.SISubscriptionInfo = SISubscriptionInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusCodes", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetStatusCodesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public string UnregisteredUserEmail;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public string UserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
    public string Password;
    
    public GetStatusCodesRequest()
    {
    }
    
    public GetStatusCodesRequest(string UnregisteredUserEmail, string UserID, string Password)
    {
        this.UnregisteredUserEmail = UnregisteredUserEmail;
        this.UserID = UserID;
        this.Password = Password;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusCodesResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetStatusCodesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public SIWsOutputOfSIWsResultArrayOfMethodStatusRecord GetStatusCodesResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public SISubscriptionInfo SISubscriptionInfo;
    
    public GetStatusCodesResponse()
    {
    }
    
    public GetStatusCodesResponse(SIWsOutputOfSIWsResultArrayOfMethodStatusRecord GetStatusCodesResult, SISubscriptionInfo SISubscriptionInfo)
    {
        this.GetStatusCodesResult = GetStatusCodesResult;
        this.SISubscriptionInfo = SISubscriptionInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceInfo", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetServiceInfoRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public string UnregisteredUserEmail;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public string UserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
    public string Password;
    
    public GetServiceInfoRequest()
    {
    }
    
    public GetServiceInfoRequest(string UnregisteredUserEmail, string UserID, string Password)
    {
        this.UnregisteredUserEmail = UnregisteredUserEmail;
        this.UserID = UserID;
        this.Password = Password;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceInfoResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetServiceInfoResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public SIWsOutputOfSIWsResultArrayOfServiceInfoRecord GetServiceInfoResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public SISubscriptionInfo SISubscriptionInfo;
    
    public GetServiceInfoResponse()
    {
    }
    
    public GetServiceInfoResponse(SIWsOutputOfSIWsResultArrayOfServiceInfoRecord GetServiceInfoResult, SISubscriptionInfo SISubscriptionInfo)
    {
        this.GetServiceInfoResult = GetServiceInfoResult;
        this.SISubscriptionInfo = SISubscriptionInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="SILicenseInfo", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetRemainingHitsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public string UnregisteredUserEmail;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public string UserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
    public string Password;
    
    public GetRemainingHitsRequest()
    {
    }
    
    public GetRemainingHitsRequest(string UnregisteredUserEmail, string UserID, string Password)
    {
        this.UnregisteredUserEmail = UnregisteredUserEmail;
        this.UserID = UserID;
        this.Password = Password;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.MessageContractAttribute(WrapperName="SISubscriptionInfo", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
public partial class GetRemainingHitsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
    public int LicenseStatusCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
    public string LicenseStatus;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
    public int LicenseActionCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=3)]
    public string LicenseAction;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=4)]
    public int RemainingHits;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=5)]
    public decimal Amount;
    
    public GetRemainingHitsResponse()
    {
    }
    
    public GetRemainingHitsResponse(int LicenseStatusCode, string LicenseStatus, int LicenseActionCode, string LicenseAction, int RemainingHits, decimal Amount)
    {
        this.LicenseStatusCode = LicenseStatusCode;
        this.LicenseStatus = LicenseStatus;
        this.LicenseActionCode = LicenseActionCode;
        this.LicenseAction = LicenseAction;
        this.RemainingHits = RemainingHits;
        this.Amount = Amount;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
public interface CurrencyRatesSoapChannel : CurrencyRatesSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
public partial class CurrencyRatesSoapClient : System.ServiceModel.ClientBase<CurrencyRatesSoap>, CurrencyRatesSoap
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public CurrencyRatesSoapClient() : 
            base(CurrencyRatesSoapClient.GetDefaultBinding(), CurrencyRatesSoapClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.CurrencyRatesSoap.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public CurrencyRatesSoapClient(EndpointConfiguration endpointConfiguration) : 
            base(CurrencyRatesSoapClient.GetBindingForEndpoint(endpointConfiguration), CurrencyRatesSoapClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public CurrencyRatesSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(CurrencyRatesSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public CurrencyRatesSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(CurrencyRatesSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public CurrencyRatesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<GetLatestRateResponse> GetLatestRateAsync(GetLatestRateRequest request)
    {
        return base.Channel.GetLatestRateAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetLatestRatesResponse> GetLatestRatesAsync(GetLatestRatesRequest request)
    {
        return base.Channel.GetLatestRatesAsync(request);
    }
    
    public System.Threading.Tasks.Task<CurrencyRateForAmountResponse> CurrencyRateForAmountAsync(CurrencyRateForAmountRequest request)
    {
        return base.Channel.CurrencyRateForAmountAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetHistoricalRatesResponse> GetHistoricalRatesAsync(GetHistoricalRatesRequest request)
    {
        return base.Channel.GetHistoricalRatesAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetHistoricalRateResponse> GetHistoricalRateAsync(GetHistoricalRateRequest request)
    {
        return base.Channel.GetHistoricalRateAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetAllLatestRatesToUSDResponse> GetAllLatestRatesToUSDAsync(GetAllLatestRatesToUSDRequest request)
    {
        return base.Channel.GetAllLatestRatesToUSDAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetAllLatestUSDToCurrenciesResponse> GetAllLatestUSDToCurrenciesAsync(GetAllLatestUSDToCurrenciesRequest request)
    {
        return base.Channel.GetAllLatestUSDToCurrenciesAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetSupportedCurrenciesResponse> GetSupportedCurrenciesAsync(GetSupportedCurrenciesRequest request)
    {
        return base.Channel.GetSupportedCurrenciesAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetStatusCodesForMethodResponse> GetStatusCodesForMethodAsync(GetStatusCodesForMethodRequest request)
    {
        return base.Channel.GetStatusCodesForMethodAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetStatusCodesResponse> GetStatusCodesAsync(GetStatusCodesRequest request)
    {
        return base.Channel.GetStatusCodesAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetServiceInfoResponse> GetServiceInfoAsync(GetServiceInfoRequest request)
    {
        return base.Channel.GetServiceInfoAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetRemainingHitsResponse> GetRemainingHitsAsync(GetRemainingHitsRequest request)
    {
        return base.Channel.GetRemainingHitsAsync(request);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.CurrencyRatesSoap))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.CurrencyRatesSoap))
        {
            return new System.ServiceModel.EndpointAddress("http://wsparam.strikeiron.com/StrikeIron/ForeignExchangeRate3/CurrencyRates");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return CurrencyRatesSoapClient.GetBindingForEndpoint(EndpointConfiguration.CurrencyRatesSoap);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return CurrencyRatesSoapClient.GetEndpointAddress(EndpointConfiguration.CurrencyRatesSoap);
    }
    
    public enum EndpointConfiguration
    {
        
        CurrencyRatesSoap,
    }
}
