//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decisions.ForEx.StrikeIronForEx {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.strikeiron.com", ConfigurationName="StrikeIronForEx.CurrencyRatesSoap")]
    public interface CurrencyRatesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetLatestRate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
        Decisions.ForEx.StrikeIronForEx.GetLatestRateResponse GetLatestRate(Decisions.ForEx.StrikeIronForEx.GetLatestRateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetLatestRate", ReplyAction="*")]
        System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetLatestRateResponse> GetLatestRateAsync(Decisions.ForEx.StrikeIronForEx.GetLatestRateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetLatestRates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
        Decisions.ForEx.StrikeIronForEx.GetLatestRatesResponse GetLatestRates(Decisions.ForEx.StrikeIronForEx.GetLatestRatesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetLatestRates", ReplyAction="*")]
        System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetLatestRatesResponse> GetLatestRatesAsync(Decisions.ForEx.StrikeIronForEx.GetLatestRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/CurrencyRateForAmount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
        Decisions.ForEx.StrikeIronForEx.CurrencyRateForAmountResponse CurrencyRateForAmount(Decisions.ForEx.StrikeIronForEx.CurrencyRateForAmountRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/CurrencyRateForAmount", ReplyAction="*")]
        System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.CurrencyRateForAmountResponse> CurrencyRateForAmountAsync(Decisions.ForEx.StrikeIronForEx.CurrencyRateForAmountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetHistoricalRates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
        Decisions.ForEx.StrikeIronForEx.GetHistoricalRatesResponse GetHistoricalRates(Decisions.ForEx.StrikeIronForEx.GetHistoricalRatesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetHistoricalRates", ReplyAction="*")]
        System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetHistoricalRatesResponse> GetHistoricalRatesAsync(Decisions.ForEx.StrikeIronForEx.GetHistoricalRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetHistoricalRate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
        Decisions.ForEx.StrikeIronForEx.GetHistoricalRateResponse GetHistoricalRate(Decisions.ForEx.StrikeIronForEx.GetHistoricalRateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetHistoricalRate", ReplyAction="*")]
        System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetHistoricalRateResponse> GetHistoricalRateAsync(Decisions.ForEx.StrikeIronForEx.GetHistoricalRateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetAllLatestRatesToUSD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
        Decisions.ForEx.StrikeIronForEx.GetAllLatestRatesToUSDResponse GetAllLatestRatesToUSD(Decisions.ForEx.StrikeIronForEx.GetAllLatestRatesToUSDRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetAllLatestRatesToUSD", ReplyAction="*")]
        System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetAllLatestRatesToUSDResponse> GetAllLatestRatesToUSDAsync(Decisions.ForEx.StrikeIronForEx.GetAllLatestRatesToUSDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetAllLatestUSDToCurrencies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
        Decisions.ForEx.StrikeIronForEx.GetAllLatestUSDToCurrenciesResponse GetAllLatestUSDToCurrencies(Decisions.ForEx.StrikeIronForEx.GetAllLatestUSDToCurrenciesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetAllLatestUSDToCurrencies", ReplyAction="*")]
        System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetAllLatestUSDToCurrenciesResponse> GetAllLatestUSDToCurrenciesAsync(Decisions.ForEx.StrikeIronForEx.GetAllLatestUSDToCurrenciesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetSupportedCurrencies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
        Decisions.ForEx.StrikeIronForEx.GetSupportedCurrenciesResponse GetSupportedCurrencies(Decisions.ForEx.StrikeIronForEx.GetSupportedCurrenciesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetSupportedCurrencies", ReplyAction="*")]
        System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetSupportedCurrenciesResponse> GetSupportedCurrenciesAsync(Decisions.ForEx.StrikeIronForEx.GetSupportedCurrenciesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetStatusCodesForMethod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
        Decisions.ForEx.StrikeIronForEx.GetStatusCodesForMethodResponse GetStatusCodesForMethod(Decisions.ForEx.StrikeIronForEx.GetStatusCodesForMethodRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetStatusCodesForMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetStatusCodesForMethodResponse> GetStatusCodesForMethodAsync(Decisions.ForEx.StrikeIronForEx.GetStatusCodesForMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetStatusCodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
        Decisions.ForEx.StrikeIronForEx.GetStatusCodesResponse GetStatusCodes(Decisions.ForEx.StrikeIronForEx.GetStatusCodesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetStatusCodes", ReplyAction="*")]
        System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetStatusCodesResponse> GetStatusCodesAsync(Decisions.ForEx.StrikeIronForEx.GetStatusCodesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetServiceInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
        Decisions.ForEx.StrikeIronForEx.GetServiceInfoResponse GetServiceInfo(Decisions.ForEx.StrikeIronForEx.GetServiceInfoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.strikeiron.com/GetServiceInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetServiceInfoResponse> GetServiceInfoAsync(Decisions.ForEx.StrikeIronForEx.GetServiceInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsparam.strikeiron.com/StrikeIron/ForeignExchangeRate3/CurrencyRates/GetRe" +
            "mainingHits", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultArrayOfSIWsStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIWsResultWithStatus))]
        Decisions.ForEx.StrikeIronForEx.GetRemainingHitsResponse GetRemainingHits(Decisions.ForEx.StrikeIronForEx.GetRemainingHitsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsparam.strikeiron.com/StrikeIron/ForeignExchangeRate3/CurrencyRates/GetRe" +
            "mainingHits", ReplyAction="*")]
        System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetRemainingHitsResponse> GetRemainingHitsAsync(Decisions.ForEx.StrikeIronForEx.GetRemainingHitsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsOutputOfExchangeRate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SIWsStatus serviceStatusField;
        
        private ExchangeRate serviceResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SIWsStatus ServiceStatus {
            get {
                return this.serviceStatusField;
            }
            set {
                this.serviceStatusField = value;
                this.RaisePropertyChanged("ServiceStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ExchangeRate ServiceResult {
            get {
                return this.serviceResultField;
            }
            set {
                this.serviceResultField = value;
                this.RaisePropertyChanged("ServiceResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int statusNbrField;
        
        private string statusDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StatusNbr {
            get {
                return this.statusNbrField;
            }
            set {
                this.statusNbrField = value;
                this.RaisePropertyChanged("StatusNbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
                this.RaisePropertyChanged("StatusDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class ServiceInfoRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string infoKeyField;
        
        private string infoValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InfoKey {
            get {
                return this.infoKeyField;
            }
            set {
                this.infoKeyField = value;
                this.RaisePropertyChanged("InfoKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InfoValue {
            get {
                return this.infoValueField;
            }
            set {
                this.infoValueField = value;
                this.RaisePropertyChanged("InfoValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsResultArrayOfServiceInfoRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceInfoRecord[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public ServiceInfoRecord[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsOutputOfSIWsResultArrayOfServiceInfoRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SIWsStatus serviceStatusField;
        
        private SIWsResultArrayOfServiceInfoRecord serviceResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SIWsStatus ServiceStatus {
            get {
                return this.serviceStatusField;
            }
            set {
                this.serviceStatusField = value;
                this.RaisePropertyChanged("ServiceStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SIWsResultArrayOfServiceInfoRecord ServiceResult {
            get {
                return this.serviceResultField;
            }
            set {
                this.serviceResultField = value;
                this.RaisePropertyChanged("ServiceResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsResultArrayOfMethodStatusRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MethodStatusRecord[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public MethodStatusRecord[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class MethodStatusRecord : SIWsResultArrayOfSIWsStatus {
        
        private string methodNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MethodName {
            get {
                return this.methodNameField;
            }
            set {
                this.methodNameField = value;
                this.RaisePropertyChanged("MethodName");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MethodStatusRecord))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsResultArrayOfSIWsStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SIWsStatus[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public SIWsStatus[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsOutputOfSIWsResultArrayOfMethodStatusRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SIWsStatus serviceStatusField;
        
        private SIWsResultArrayOfMethodStatusRecord serviceResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SIWsStatus ServiceStatus {
            get {
                return this.serviceStatusField;
            }
            set {
                this.serviceStatusField = value;
                this.RaisePropertyChanged("ServiceStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SIWsResultArrayOfMethodStatusRecord ServiceResult {
            get {
                return this.serviceResultField;
            }
            set {
                this.serviceResultField = value;
                this.RaisePropertyChanged("ServiceResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsOutputOfMethodStatusRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SIWsStatus serviceStatusField;
        
        private MethodStatusRecord serviceResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SIWsStatus ServiceStatus {
            get {
                return this.serviceStatusField;
            }
            set {
                this.serviceStatusField = value;
                this.RaisePropertyChanged("ServiceStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MethodStatusRecord ServiceResult {
            get {
                return this.serviceResultField;
            }
            set {
                this.serviceResultField = value;
                this.RaisePropertyChanged("ServiceResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class CurrencyListing : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string unitField;
        
        private string countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsResultArrayOfCurrencyListing : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CurrencyListing[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public CurrencyListing[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsOutputOfSIWsResultArrayOfCurrencyListing : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SIWsStatus serviceStatusField;
        
        private SIWsResultArrayOfCurrencyListing serviceResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SIWsStatus ServiceStatus {
            get {
                return this.serviceStatusField;
            }
            set {
                this.serviceStatusField = value;
                this.RaisePropertyChanged("ServiceStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SIWsResultArrayOfCurrencyListing ServiceResult {
            get {
                return this.serviceResultField;
            }
            set {
                this.serviceResultField = value;
                this.RaisePropertyChanged("ServiceResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExchangeRateListing))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public abstract partial class SIWsResultWithStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SIWsStatus itemStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SIWsStatus ItemStatus {
            get {
                return this.itemStatusField;
            }
            set {
                this.itemStatusField = value;
                this.RaisePropertyChanged("ItemStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class ExchangeRateListing : SIWsResultWithStatus {
        
        private double valueField;
        
        private string currencyField;
        
        private string perCurrencyField;
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PerCurrency {
            get {
                return this.perCurrencyField;
            }
            set {
                this.perCurrencyField = value;
                this.RaisePropertyChanged("PerCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsResultArrayOfExchangeRateListing : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExchangeRateListing[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public ExchangeRateListing[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SIWsOutputOfSIWsResultArrayOfExchangeRateListing : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SIWsStatus serviceStatusField;
        
        private SIWsResultArrayOfExchangeRateListing serviceResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SIWsStatus ServiceStatus {
            get {
                return this.serviceStatusField;
            }
            set {
                this.serviceStatusField = value;
                this.RaisePropertyChanged("ServiceStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SIWsResultArrayOfExchangeRateListing ServiceResult {
            get {
                return this.serviceResultField;
            }
            set {
                this.serviceResultField = value;
                this.RaisePropertyChanged("ServiceResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class SISubscriptionInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int licenseStatusCodeField;
        
        private string licenseStatusField;
        
        private int licenseActionCodeField;
        
        private string licenseActionField;
        
        private int remainingHitsField;
        
        private decimal amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int LicenseStatusCode {
            get {
                return this.licenseStatusCodeField;
            }
            set {
                this.licenseStatusCodeField = value;
                this.RaisePropertyChanged("LicenseStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LicenseStatus {
            get {
                return this.licenseStatusField;
            }
            set {
                this.licenseStatusField = value;
                this.RaisePropertyChanged("LicenseStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int LicenseActionCode {
            get {
                return this.licenseActionCodeField;
            }
            set {
                this.licenseActionCodeField = value;
                this.RaisePropertyChanged("LicenseActionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LicenseAction {
            get {
                return this.licenseActionField;
            }
            set {
                this.licenseActionField = value;
                this.RaisePropertyChanged("LicenseAction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int RemainingHits {
            get {
                return this.remainingHitsField;
            }
            set {
                this.remainingHitsField = value;
                this.RaisePropertyChanged("RemainingHits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class ExchangeRate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double valueField;
        
        private string currencyField;
        
        private string perCurrencyField;
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PerCurrency {
            get {
                return this.perCurrencyField;
            }
            set {
                this.perCurrencyField = value;
                this.RaisePropertyChanged("PerCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLatestRate", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetLatestRateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public string UnregisteredUserEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=3)]
        public string SingleCurrencyFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=4)]
        public string SingleCurrencyTo;
        
        public GetLatestRateRequest() {
        }
        
        public GetLatestRateRequest(string UnregisteredUserEmail, string UserID, string Password, string SingleCurrencyFrom, string SingleCurrencyTo) {
            this.UnregisteredUserEmail = UnregisteredUserEmail;
            this.UserID = UserID;
            this.Password = Password;
            this.SingleCurrencyFrom = SingleCurrencyFrom;
            this.SingleCurrencyTo = SingleCurrencyTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLatestRateResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetLatestRateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfExchangeRate GetLatestRateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo;
        
        public GetLatestRateResponse() {
        }
        
        public GetLatestRateResponse(Decisions.ForEx.StrikeIronForEx.SIWsOutputOfExchangeRate GetLatestRateResult, Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            this.GetLatestRateResult = GetLatestRateResult;
            this.SISubscriptionInfo = SISubscriptionInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLatestRates", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetLatestRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public string UnregisteredUserEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=3)]
        public string CommaSeparatedListOfCurrenciesFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=4)]
        public string SingleCurrencyTo;
        
        public GetLatestRatesRequest() {
        }
        
        public GetLatestRatesRequest(string UnregisteredUserEmail, string UserID, string Password, string CommaSeparatedListOfCurrenciesFrom, string SingleCurrencyTo) {
            this.UnregisteredUserEmail = UnregisteredUserEmail;
            this.UserID = UserID;
            this.Password = Password;
            this.CommaSeparatedListOfCurrenciesFrom = CommaSeparatedListOfCurrenciesFrom;
            this.SingleCurrencyTo = SingleCurrencyTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLatestRatesResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetLatestRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetLatestRatesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo;
        
        public GetLatestRatesResponse() {
        }
        
        public GetLatestRatesResponse(Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetLatestRatesResult, Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            this.GetLatestRatesResult = GetLatestRatesResult;
            this.SISubscriptionInfo = SISubscriptionInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CurrencyRateForAmount", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class CurrencyRateForAmountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public string UnregisteredUserEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=3)]
        public string SingleCurrencyFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=4)]
        public string SingleCurrencyTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=5)]
        public string Amount;
        
        public CurrencyRateForAmountRequest() {
        }
        
        public CurrencyRateForAmountRequest(string UnregisteredUserEmail, string UserID, string Password, string SingleCurrencyFrom, string SingleCurrencyTo, string Amount) {
            this.UnregisteredUserEmail = UnregisteredUserEmail;
            this.UserID = UserID;
            this.Password = Password;
            this.SingleCurrencyFrom = SingleCurrencyFrom;
            this.SingleCurrencyTo = SingleCurrencyTo;
            this.Amount = Amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CurrencyRateForAmountResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class CurrencyRateForAmountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfExchangeRate CurrencyRateForAmountResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo;
        
        public CurrencyRateForAmountResponse() {
        }
        
        public CurrencyRateForAmountResponse(Decisions.ForEx.StrikeIronForEx.SIWsOutputOfExchangeRate CurrencyRateForAmountResult, Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            this.CurrencyRateForAmountResult = CurrencyRateForAmountResult;
            this.SISubscriptionInfo = SISubscriptionInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHistoricalRates", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetHistoricalRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public string UnregisteredUserEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=3)]
        public string CommaSeparatedListOfCurrenciesFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=4)]
        public string SingleCurrencyTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=5)]
        public string Date;
        
        public GetHistoricalRatesRequest() {
        }
        
        public GetHistoricalRatesRequest(string UnregisteredUserEmail, string UserID, string Password, string CommaSeparatedListOfCurrenciesFrom, string SingleCurrencyTo, string Date) {
            this.UnregisteredUserEmail = UnregisteredUserEmail;
            this.UserID = UserID;
            this.Password = Password;
            this.CommaSeparatedListOfCurrenciesFrom = CommaSeparatedListOfCurrenciesFrom;
            this.SingleCurrencyTo = SingleCurrencyTo;
            this.Date = Date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHistoricalRatesResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetHistoricalRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetHistoricalRatesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo;
        
        public GetHistoricalRatesResponse() {
        }
        
        public GetHistoricalRatesResponse(Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetHistoricalRatesResult, Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            this.GetHistoricalRatesResult = GetHistoricalRatesResult;
            this.SISubscriptionInfo = SISubscriptionInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHistoricalRate", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetHistoricalRateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public string UnregisteredUserEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=3)]
        public string SingleCurrencyFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=4)]
        public string SingleCurrencyTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=5)]
        public string DateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=6)]
        public string DateTo;
        
        public GetHistoricalRateRequest() {
        }
        
        public GetHistoricalRateRequest(string UnregisteredUserEmail, string UserID, string Password, string SingleCurrencyFrom, string SingleCurrencyTo, string DateFrom, string DateTo) {
            this.UnregisteredUserEmail = UnregisteredUserEmail;
            this.UserID = UserID;
            this.Password = Password;
            this.SingleCurrencyFrom = SingleCurrencyFrom;
            this.SingleCurrencyTo = SingleCurrencyTo;
            this.DateFrom = DateFrom;
            this.DateTo = DateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHistoricalRateResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetHistoricalRateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetHistoricalRateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo;
        
        public GetHistoricalRateResponse() {
        }
        
        public GetHistoricalRateResponse(Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetHistoricalRateResult, Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            this.GetHistoricalRateResult = GetHistoricalRateResult;
            this.SISubscriptionInfo = SISubscriptionInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllLatestRatesToUSD", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetAllLatestRatesToUSDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public string UnregisteredUserEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
        public string Password;
        
        public GetAllLatestRatesToUSDRequest() {
        }
        
        public GetAllLatestRatesToUSDRequest(string UnregisteredUserEmail, string UserID, string Password) {
            this.UnregisteredUserEmail = UnregisteredUserEmail;
            this.UserID = UserID;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllLatestRatesToUSDResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetAllLatestRatesToUSDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetAllLatestRatesToUSDResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo;
        
        public GetAllLatestRatesToUSDResponse() {
        }
        
        public GetAllLatestRatesToUSDResponse(Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetAllLatestRatesToUSDResult, Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            this.GetAllLatestRatesToUSDResult = GetAllLatestRatesToUSDResult;
            this.SISubscriptionInfo = SISubscriptionInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllLatestUSDToCurrencies", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetAllLatestUSDToCurrenciesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public string UnregisteredUserEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
        public string Password;
        
        public GetAllLatestUSDToCurrenciesRequest() {
        }
        
        public GetAllLatestUSDToCurrenciesRequest(string UnregisteredUserEmail, string UserID, string Password) {
            this.UnregisteredUserEmail = UnregisteredUserEmail;
            this.UserID = UserID;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllLatestUSDToCurrenciesResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetAllLatestUSDToCurrenciesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetAllLatestUSDToCurrenciesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo;
        
        public GetAllLatestUSDToCurrenciesResponse() {
        }
        
        public GetAllLatestUSDToCurrenciesResponse(Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetAllLatestUSDToCurrenciesResult, Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            this.GetAllLatestUSDToCurrenciesResult = GetAllLatestUSDToCurrenciesResult;
            this.SISubscriptionInfo = SISubscriptionInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSupportedCurrencies", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetSupportedCurrenciesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public string UnregisteredUserEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
        public string Password;
        
        public GetSupportedCurrenciesRequest() {
        }
        
        public GetSupportedCurrenciesRequest(string UnregisteredUserEmail, string UserID, string Password) {
            this.UnregisteredUserEmail = UnregisteredUserEmail;
            this.UserID = UserID;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSupportedCurrenciesResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetSupportedCurrenciesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfCurrencyListing GetSupportedCurrenciesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo;
        
        public GetSupportedCurrenciesResponse() {
        }
        
        public GetSupportedCurrenciesResponse(Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfCurrencyListing GetSupportedCurrenciesResult, Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            this.GetSupportedCurrenciesResult = GetSupportedCurrenciesResult;
            this.SISubscriptionInfo = SISubscriptionInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusCodesForMethod", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetStatusCodesForMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public string UnregisteredUserEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=3)]
        public string MethodName;
        
        public GetStatusCodesForMethodRequest() {
        }
        
        public GetStatusCodesForMethodRequest(string UnregisteredUserEmail, string UserID, string Password, string MethodName) {
            this.UnregisteredUserEmail = UnregisteredUserEmail;
            this.UserID = UserID;
            this.Password = Password;
            this.MethodName = MethodName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusCodesForMethodResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetStatusCodesForMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfMethodStatusRecord GetStatusCodesForMethodResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo;
        
        public GetStatusCodesForMethodResponse() {
        }
        
        public GetStatusCodesForMethodResponse(Decisions.ForEx.StrikeIronForEx.SIWsOutputOfMethodStatusRecord GetStatusCodesForMethodResult, Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            this.GetStatusCodesForMethodResult = GetStatusCodesForMethodResult;
            this.SISubscriptionInfo = SISubscriptionInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusCodes", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetStatusCodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public string UnregisteredUserEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
        public string Password;
        
        public GetStatusCodesRequest() {
        }
        
        public GetStatusCodesRequest(string UnregisteredUserEmail, string UserID, string Password) {
            this.UnregisteredUserEmail = UnregisteredUserEmail;
            this.UserID = UserID;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusCodesResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetStatusCodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfMethodStatusRecord GetStatusCodesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo;
        
        public GetStatusCodesResponse() {
        }
        
        public GetStatusCodesResponse(Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfMethodStatusRecord GetStatusCodesResult, Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            this.GetStatusCodesResult = GetStatusCodesResult;
            this.SISubscriptionInfo = SISubscriptionInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceInfo", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetServiceInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public string UnregisteredUserEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
        public string Password;
        
        public GetServiceInfoRequest() {
        }
        
        public GetServiceInfoRequest(string UnregisteredUserEmail, string UserID, string Password) {
            this.UnregisteredUserEmail = UnregisteredUserEmail;
            this.UserID = UserID;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceInfoResponse", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetServiceInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfServiceInfoRecord GetServiceInfoResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo;
        
        public GetServiceInfoResponse() {
        }
        
        public GetServiceInfoResponse(Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfServiceInfoRecord GetServiceInfoResult, Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            this.GetServiceInfoResult = GetServiceInfoResult;
            this.SISubscriptionInfo = SISubscriptionInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SILicenseInfo", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetRemainingHitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public string UnregisteredUserEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
        public string Password;
        
        public GetRemainingHitsRequest() {
        }
        
        public GetRemainingHitsRequest(string UnregisteredUserEmail, string UserID, string Password) {
            this.UnregisteredUserEmail = UnregisteredUserEmail;
            this.UserID = UserID;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SISubscriptionInfo", WrapperNamespace="http://www.strikeiron.com", IsWrapped=true)]
    public partial class GetRemainingHitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=0)]
        public int LicenseStatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=1)]
        public string LicenseStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=2)]
        public int LicenseActionCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=3)]
        public string LicenseAction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=4)]
        public int RemainingHits;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.strikeiron.com", Order=5)]
        public decimal Amount;
        
        public GetRemainingHitsResponse() {
        }
        
        public GetRemainingHitsResponse(int LicenseStatusCode, string LicenseStatus, int LicenseActionCode, string LicenseAction, int RemainingHits, decimal Amount) {
            this.LicenseStatusCode = LicenseStatusCode;
            this.LicenseStatus = LicenseStatus;
            this.LicenseActionCode = LicenseActionCode;
            this.LicenseAction = LicenseAction;
            this.RemainingHits = RemainingHits;
            this.Amount = Amount;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CurrencyRatesSoapChannel : Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencyRatesSoapClient : System.ServiceModel.ClientBase<Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap>, Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap {
        
        public CurrencyRatesSoapClient() {
        }
        
        public CurrencyRatesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrencyRatesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyRatesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyRatesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Decisions.ForEx.StrikeIronForEx.GetLatestRateResponse Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap.GetLatestRate(Decisions.ForEx.StrikeIronForEx.GetLatestRateRequest request) {
            return base.Channel.GetLatestRate(request);
        }
        
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfExchangeRate GetLatestRate(string UnregisteredUserEmail, string UserID, string Password, string SingleCurrencyFrom, string SingleCurrencyTo, out Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            Decisions.ForEx.StrikeIronForEx.GetLatestRateRequest inValue = new Decisions.ForEx.StrikeIronForEx.GetLatestRateRequest();
            inValue.UnregisteredUserEmail = UnregisteredUserEmail;
            inValue.UserID = UserID;
            inValue.Password = Password;
            inValue.SingleCurrencyFrom = SingleCurrencyFrom;
            inValue.SingleCurrencyTo = SingleCurrencyTo;
            Decisions.ForEx.StrikeIronForEx.GetLatestRateResponse retVal = ((Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap)(this)).GetLatestRate(inValue);
            SISubscriptionInfo = retVal.SISubscriptionInfo;
            return retVal.GetLatestRateResult;
        }
        
        public System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetLatestRateResponse> GetLatestRateAsync(Decisions.ForEx.StrikeIronForEx.GetLatestRateRequest request) {
            return base.Channel.GetLatestRateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Decisions.ForEx.StrikeIronForEx.GetLatestRatesResponse Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap.GetLatestRates(Decisions.ForEx.StrikeIronForEx.GetLatestRatesRequest request) {
            return base.Channel.GetLatestRates(request);
        }
        
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetLatestRates(string UnregisteredUserEmail, string UserID, string Password, string CommaSeparatedListOfCurrenciesFrom, string SingleCurrencyTo, out Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            Decisions.ForEx.StrikeIronForEx.GetLatestRatesRequest inValue = new Decisions.ForEx.StrikeIronForEx.GetLatestRatesRequest();
            inValue.UnregisteredUserEmail = UnregisteredUserEmail;
            inValue.UserID = UserID;
            inValue.Password = Password;
            inValue.CommaSeparatedListOfCurrenciesFrom = CommaSeparatedListOfCurrenciesFrom;
            inValue.SingleCurrencyTo = SingleCurrencyTo;
            Decisions.ForEx.StrikeIronForEx.GetLatestRatesResponse retVal = ((Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap)(this)).GetLatestRates(inValue);
            SISubscriptionInfo = retVal.SISubscriptionInfo;
            return retVal.GetLatestRatesResult;
        }
        
        public System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetLatestRatesResponse> GetLatestRatesAsync(Decisions.ForEx.StrikeIronForEx.GetLatestRatesRequest request) {
            return base.Channel.GetLatestRatesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Decisions.ForEx.StrikeIronForEx.CurrencyRateForAmountResponse Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap.CurrencyRateForAmount(Decisions.ForEx.StrikeIronForEx.CurrencyRateForAmountRequest request) {
            return base.Channel.CurrencyRateForAmount(request);
        }
        
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfExchangeRate CurrencyRateForAmount(string UnregisteredUserEmail, string UserID, string Password, string SingleCurrencyFrom, string SingleCurrencyTo, string Amount, out Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            Decisions.ForEx.StrikeIronForEx.CurrencyRateForAmountRequest inValue = new Decisions.ForEx.StrikeIronForEx.CurrencyRateForAmountRequest();
            inValue.UnregisteredUserEmail = UnregisteredUserEmail;
            inValue.UserID = UserID;
            inValue.Password = Password;
            inValue.SingleCurrencyFrom = SingleCurrencyFrom;
            inValue.SingleCurrencyTo = SingleCurrencyTo;
            inValue.Amount = Amount;
            Decisions.ForEx.StrikeIronForEx.CurrencyRateForAmountResponse retVal = ((Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap)(this)).CurrencyRateForAmount(inValue);
            SISubscriptionInfo = retVal.SISubscriptionInfo;
            return retVal.CurrencyRateForAmountResult;
        }
        
        public System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.CurrencyRateForAmountResponse> CurrencyRateForAmountAsync(Decisions.ForEx.StrikeIronForEx.CurrencyRateForAmountRequest request) {
            return base.Channel.CurrencyRateForAmountAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Decisions.ForEx.StrikeIronForEx.GetHistoricalRatesResponse Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap.GetHistoricalRates(Decisions.ForEx.StrikeIronForEx.GetHistoricalRatesRequest request) {
            return base.Channel.GetHistoricalRates(request);
        }
        
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetHistoricalRates(string UnregisteredUserEmail, string UserID, string Password, string CommaSeparatedListOfCurrenciesFrom, string SingleCurrencyTo, string Date, out Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            Decisions.ForEx.StrikeIronForEx.GetHistoricalRatesRequest inValue = new Decisions.ForEx.StrikeIronForEx.GetHistoricalRatesRequest();
            inValue.UnregisteredUserEmail = UnregisteredUserEmail;
            inValue.UserID = UserID;
            inValue.Password = Password;
            inValue.CommaSeparatedListOfCurrenciesFrom = CommaSeparatedListOfCurrenciesFrom;
            inValue.SingleCurrencyTo = SingleCurrencyTo;
            inValue.Date = Date;
            Decisions.ForEx.StrikeIronForEx.GetHistoricalRatesResponse retVal = ((Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap)(this)).GetHistoricalRates(inValue);
            SISubscriptionInfo = retVal.SISubscriptionInfo;
            return retVal.GetHistoricalRatesResult;
        }
        
        public System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetHistoricalRatesResponse> GetHistoricalRatesAsync(Decisions.ForEx.StrikeIronForEx.GetHistoricalRatesRequest request) {
            return base.Channel.GetHistoricalRatesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Decisions.ForEx.StrikeIronForEx.GetHistoricalRateResponse Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap.GetHistoricalRate(Decisions.ForEx.StrikeIronForEx.GetHistoricalRateRequest request) {
            return base.Channel.GetHistoricalRate(request);
        }
        
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetHistoricalRate(string UnregisteredUserEmail, string UserID, string Password, string SingleCurrencyFrom, string SingleCurrencyTo, string DateFrom, string DateTo, out Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            Decisions.ForEx.StrikeIronForEx.GetHistoricalRateRequest inValue = new Decisions.ForEx.StrikeIronForEx.GetHistoricalRateRequest();
            inValue.UnregisteredUserEmail = UnregisteredUserEmail;
            inValue.UserID = UserID;
            inValue.Password = Password;
            inValue.SingleCurrencyFrom = SingleCurrencyFrom;
            inValue.SingleCurrencyTo = SingleCurrencyTo;
            inValue.DateFrom = DateFrom;
            inValue.DateTo = DateTo;
            Decisions.ForEx.StrikeIronForEx.GetHistoricalRateResponse retVal = ((Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap)(this)).GetHistoricalRate(inValue);
            SISubscriptionInfo = retVal.SISubscriptionInfo;
            return retVal.GetHistoricalRateResult;
        }
        
        public System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetHistoricalRateResponse> GetHistoricalRateAsync(Decisions.ForEx.StrikeIronForEx.GetHistoricalRateRequest request) {
            return base.Channel.GetHistoricalRateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Decisions.ForEx.StrikeIronForEx.GetAllLatestRatesToUSDResponse Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap.GetAllLatestRatesToUSD(Decisions.ForEx.StrikeIronForEx.GetAllLatestRatesToUSDRequest request) {
            return base.Channel.GetAllLatestRatesToUSD(request);
        }
        
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetAllLatestRatesToUSD(string UnregisteredUserEmail, string UserID, string Password, out Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            Decisions.ForEx.StrikeIronForEx.GetAllLatestRatesToUSDRequest inValue = new Decisions.ForEx.StrikeIronForEx.GetAllLatestRatesToUSDRequest();
            inValue.UnregisteredUserEmail = UnregisteredUserEmail;
            inValue.UserID = UserID;
            inValue.Password = Password;
            Decisions.ForEx.StrikeIronForEx.GetAllLatestRatesToUSDResponse retVal = ((Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap)(this)).GetAllLatestRatesToUSD(inValue);
            SISubscriptionInfo = retVal.SISubscriptionInfo;
            return retVal.GetAllLatestRatesToUSDResult;
        }
        
        public System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetAllLatestRatesToUSDResponse> GetAllLatestRatesToUSDAsync(Decisions.ForEx.StrikeIronForEx.GetAllLatestRatesToUSDRequest request) {
            return base.Channel.GetAllLatestRatesToUSDAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Decisions.ForEx.StrikeIronForEx.GetAllLatestUSDToCurrenciesResponse Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap.GetAllLatestUSDToCurrencies(Decisions.ForEx.StrikeIronForEx.GetAllLatestUSDToCurrenciesRequest request) {
            return base.Channel.GetAllLatestUSDToCurrencies(request);
        }
        
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfExchangeRateListing GetAllLatestUSDToCurrencies(string UnregisteredUserEmail, string UserID, string Password, out Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            Decisions.ForEx.StrikeIronForEx.GetAllLatestUSDToCurrenciesRequest inValue = new Decisions.ForEx.StrikeIronForEx.GetAllLatestUSDToCurrenciesRequest();
            inValue.UnregisteredUserEmail = UnregisteredUserEmail;
            inValue.UserID = UserID;
            inValue.Password = Password;
            Decisions.ForEx.StrikeIronForEx.GetAllLatestUSDToCurrenciesResponse retVal = ((Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap)(this)).GetAllLatestUSDToCurrencies(inValue);
            SISubscriptionInfo = retVal.SISubscriptionInfo;
            return retVal.GetAllLatestUSDToCurrenciesResult;
        }
        
        public System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetAllLatestUSDToCurrenciesResponse> GetAllLatestUSDToCurrenciesAsync(Decisions.ForEx.StrikeIronForEx.GetAllLatestUSDToCurrenciesRequest request) {
            return base.Channel.GetAllLatestUSDToCurrenciesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Decisions.ForEx.StrikeIronForEx.GetSupportedCurrenciesResponse Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap.GetSupportedCurrencies(Decisions.ForEx.StrikeIronForEx.GetSupportedCurrenciesRequest request) {
            return base.Channel.GetSupportedCurrencies(request);
        }
        
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfCurrencyListing GetSupportedCurrencies(string UnregisteredUserEmail, string UserID, string Password, out Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            Decisions.ForEx.StrikeIronForEx.GetSupportedCurrenciesRequest inValue = new Decisions.ForEx.StrikeIronForEx.GetSupportedCurrenciesRequest();
            inValue.UnregisteredUserEmail = UnregisteredUserEmail;
            inValue.UserID = UserID;
            inValue.Password = Password;
            Decisions.ForEx.StrikeIronForEx.GetSupportedCurrenciesResponse retVal = ((Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap)(this)).GetSupportedCurrencies(inValue);
            SISubscriptionInfo = retVal.SISubscriptionInfo;
            return retVal.GetSupportedCurrenciesResult;
        }
        
        public System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetSupportedCurrenciesResponse> GetSupportedCurrenciesAsync(Decisions.ForEx.StrikeIronForEx.GetSupportedCurrenciesRequest request) {
            return base.Channel.GetSupportedCurrenciesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Decisions.ForEx.StrikeIronForEx.GetStatusCodesForMethodResponse Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap.GetStatusCodesForMethod(Decisions.ForEx.StrikeIronForEx.GetStatusCodesForMethodRequest request) {
            return base.Channel.GetStatusCodesForMethod(request);
        }
        
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfMethodStatusRecord GetStatusCodesForMethod(string UnregisteredUserEmail, string UserID, string Password, string MethodName, out Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            Decisions.ForEx.StrikeIronForEx.GetStatusCodesForMethodRequest inValue = new Decisions.ForEx.StrikeIronForEx.GetStatusCodesForMethodRequest();
            inValue.UnregisteredUserEmail = UnregisteredUserEmail;
            inValue.UserID = UserID;
            inValue.Password = Password;
            inValue.MethodName = MethodName;
            Decisions.ForEx.StrikeIronForEx.GetStatusCodesForMethodResponse retVal = ((Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap)(this)).GetStatusCodesForMethod(inValue);
            SISubscriptionInfo = retVal.SISubscriptionInfo;
            return retVal.GetStatusCodesForMethodResult;
        }
        
        public System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetStatusCodesForMethodResponse> GetStatusCodesForMethodAsync(Decisions.ForEx.StrikeIronForEx.GetStatusCodesForMethodRequest request) {
            return base.Channel.GetStatusCodesForMethodAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Decisions.ForEx.StrikeIronForEx.GetStatusCodesResponse Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap.GetStatusCodes(Decisions.ForEx.StrikeIronForEx.GetStatusCodesRequest request) {
            return base.Channel.GetStatusCodes(request);
        }
        
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfMethodStatusRecord GetStatusCodes(string UnregisteredUserEmail, string UserID, string Password, out Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            Decisions.ForEx.StrikeIronForEx.GetStatusCodesRequest inValue = new Decisions.ForEx.StrikeIronForEx.GetStatusCodesRequest();
            inValue.UnregisteredUserEmail = UnregisteredUserEmail;
            inValue.UserID = UserID;
            inValue.Password = Password;
            Decisions.ForEx.StrikeIronForEx.GetStatusCodesResponse retVal = ((Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap)(this)).GetStatusCodes(inValue);
            SISubscriptionInfo = retVal.SISubscriptionInfo;
            return retVal.GetStatusCodesResult;
        }
        
        public System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetStatusCodesResponse> GetStatusCodesAsync(Decisions.ForEx.StrikeIronForEx.GetStatusCodesRequest request) {
            return base.Channel.GetStatusCodesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Decisions.ForEx.StrikeIronForEx.GetServiceInfoResponse Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap.GetServiceInfo(Decisions.ForEx.StrikeIronForEx.GetServiceInfoRequest request) {
            return base.Channel.GetServiceInfo(request);
        }
        
        public Decisions.ForEx.StrikeIronForEx.SIWsOutputOfSIWsResultArrayOfServiceInfoRecord GetServiceInfo(string UnregisteredUserEmail, string UserID, string Password, out Decisions.ForEx.StrikeIronForEx.SISubscriptionInfo SISubscriptionInfo) {
            Decisions.ForEx.StrikeIronForEx.GetServiceInfoRequest inValue = new Decisions.ForEx.StrikeIronForEx.GetServiceInfoRequest();
            inValue.UnregisteredUserEmail = UnregisteredUserEmail;
            inValue.UserID = UserID;
            inValue.Password = Password;
            Decisions.ForEx.StrikeIronForEx.GetServiceInfoResponse retVal = ((Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap)(this)).GetServiceInfo(inValue);
            SISubscriptionInfo = retVal.SISubscriptionInfo;
            return retVal.GetServiceInfoResult;
        }
        
        public System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetServiceInfoResponse> GetServiceInfoAsync(Decisions.ForEx.StrikeIronForEx.GetServiceInfoRequest request) {
            return base.Channel.GetServiceInfoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Decisions.ForEx.StrikeIronForEx.GetRemainingHitsResponse Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap.GetRemainingHits(Decisions.ForEx.StrikeIronForEx.GetRemainingHitsRequest request) {
            return base.Channel.GetRemainingHits(request);
        }
        
        public int GetRemainingHits(string UnregisteredUserEmail, string UserID, string Password, out string LicenseStatus, out int LicenseActionCode, out string LicenseAction, out int RemainingHits, out decimal Amount) {
            Decisions.ForEx.StrikeIronForEx.GetRemainingHitsRequest inValue = new Decisions.ForEx.StrikeIronForEx.GetRemainingHitsRequest();
            inValue.UnregisteredUserEmail = UnregisteredUserEmail;
            inValue.UserID = UserID;
            inValue.Password = Password;
            Decisions.ForEx.StrikeIronForEx.GetRemainingHitsResponse retVal = ((Decisions.ForEx.StrikeIronForEx.CurrencyRatesSoap)(this)).GetRemainingHits(inValue);
            LicenseStatus = retVal.LicenseStatus;
            LicenseActionCode = retVal.LicenseActionCode;
            LicenseAction = retVal.LicenseAction;
            RemainingHits = retVal.RemainingHits;
            Amount = retVal.Amount;
            return retVal.LicenseStatusCode;
        }
        
        public System.Threading.Tasks.Task<Decisions.ForEx.StrikeIronForEx.GetRemainingHitsResponse> GetRemainingHitsAsync(Decisions.ForEx.StrikeIronForEx.GetRemainingHitsRequest request) {
            return base.Channel.GetRemainingHitsAsync(request);
        }
    }
}
